language: ruby
cache: bundler
rvm:
  - 2.3.1
notifications:
  email:
    - api@mrcr.ru
script:
    - bundle exec rake
before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick
  - gem update bundler